### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by grillermo** [celery/django-celery#143]
Hi, reading the docs it says that i need to set
    CELERY_RESULT_BACKEND = "redis://:password@host:port/db"
Problem is with this setting i get an error that says
    Import by filename is not supported.

i got a url from a heroku service called redistogo that looks like
redis://redistogo:RANDOMPASSWORD@somedomain.com:8393/

I'm trying to setup redis as my broker and backend, as i said this configuration
   BROKER_URL = 'redis://redistogo:RANDOMPASSWORD@somedomain.com:8393/'
   CELERY_RESULT_BACKEND = redis://redistogo:RANDOMPASSWORD@somedomain.com:8393/
Doesnt work, i tried different combinations of configurations including separating each 
    CELERY_REDIS_PORT = 8393
    CELERY_REDIS_PASSWORD = 'RANDOMPASSWORD'
    CELERY_REDIS_HOST = somedomain.com
without much success.
I would be happy with a working set of settings.

I'm confused by the different settings published on the celery readthedocs and the github
readthedocs.org/docs/celery-docs/
celery.github.com/celery/configuration.html
They are not conflicting, but they say different things about getting redis to work with celery as a backend and as a broker.

Any help appreciated.

**Comment by kartikdanidhariya** [comment]
hi ,
i search in addons in heroku for redistogo but nit find any match 
can you please specify how we add this in heroku app
