### ISSUE TITLE
Migrations broken in django-celery 3.0

### ISSUE THREAD

**Issue by zain** [celery/django-celery#149]
On a fresh project using sqlite3, djcelery, and south, running migrate throws the following error:

```
$ python manage.py migrate
Running migrations for djcelery:
 - Migrating forwards to 0004_v30_changes.
 > djcelery:0001_initial
 > djcelery:0002_v25_changes
FATAL ERROR - The following SQL query failed: CREATE TABLE "celery_taskmeta" ("id" integer NOT NULL PRIMARY KEY, "task_id" varchar(255) NOT NULL UNIQUE, "status" varchar(50) NOT NULL DEFAULT 'PENDING', "result" text NULL, "date_done" datetime NOT NULL, "traceback" text NULL);
The error was: table "celery_taskmeta" already exists
FATAL ERROR - The following SQL query failed: CREATE TABLE "celery_tasksetmeta" ("id" integer NOT NULL PRIMARY KEY, "taskset_id" varchar(255) NOT NULL UNIQUE, "result" text NOT NULL, "date_done" datetime NOT NULL);
The error was: table "celery_tasksetmeta" already exists
 > djcelery:0003_v26_changes
 > djcelery:0004_v30_changes
 - Loading initial data for djcelery.
Installed 0 object(s) from 0 fixture(s)
```

**Comment by Oxtay** [comment]
I followed the steps suggested above but they didn't seem to work. I was trying to re-install the packages I had in my virtualenv which were:
```
amqp==1.4.6
anyjson==0.3.3
apns-clerk==0.1.1
arrow==0.4.1
backports.ssl-match-hostname==3.4.0.2
billiard==3.3.0.19
bootstrap-admin==0.3.0
boto==2.25.0
celery==3.1.17
certifi==14.5.14
cffi==0.8.6
cryptography==0.7.1
Cython==0.19.1
dill==0.2.1
Django==1.6.1
django-appconf==0.6
django-bower==4.8.1
django-celery==3.1.0
django-compressor==1.3
django-debug-toolbar==1.2
django-extensions==1.4.9
django-gravatar2==1.1.3
django-picklefield==0.3.1
django-resized==0.2.4
django-ses==0.6.0
djangorestframework==2.3.8
enum34==1.0.4
gcm-client==0.1.4
Jinja2==2.7.3
joblib==0.8.0a3
kombu==3.0.24
line-profiler==1.0b3
MarkupSafe==0.23
mlpy==3.5.0
mock==1.0.1
nose==1.3.4
numpy==1.8.0
Pillow==2.7.0
psycopg2==2.4.6
pyasn1==0.1.7
pycparser==2.10
pyOpenSSL==0.14
pyparsing==2.0.3
python-dateutil==2.2
python-memcached==1.48
python-slugify==0.1.0
pytz==2014.10
pyzmq==14.4.1
raven==3.3.7
requests==2.5.1
scipy==0.13.3
six==1.8.0
South==0.7.6
sqlparse==0.1.11
tornado==4.0.2
Unidecode==0.4.17
yattag==1.0.7
```

Celery was functioning normally and nothing seemed to have changed but now I get this error

`ProgrammingError: relation “celery_taskmeta” does not exist`

From what I understand from the comments above, this might not even be a problem with version incompatibility but since I don't know what exactly `celery_taskmeta` does, I am not so sure.

**Comment by adriaant** [comment]
You installed an old version of django-celery. It should be django-celery==3.1.16. Best is to install django-celery first, it will install celery as dependency. But in your case, just do a `pip install django-celery --upgrade`

**Comment by Oxtay** [comment]
Thanks but that didn't solve it unfortunately. I'm trying to figure out what else could've caused it.

**Comment by timfeirg** [comment]
I'm using  django-celery-3.1.17 & celery 3.1.19, still seeing this error:

```python
django.db.utils.OperationalError: (1050, "Table 'djcelery_crontabschedule' already exists")
```

**Comment by richardasaurus** [comment]
@timfeirg try placing this migration in your project app? https://gist.github.com/richardasaurus/802325a09a07892646f4

**Comment by bzmwillemsen** [comment]
If you are upgrading to django-celery 3.1.17 and you can't replace the library with celery (for some reason) You will experience the same issue as @timfeirg mentioned and it can be fixed by running:

```
./manage.py migrate djcelery --fake
```

**Comment by silviomoreto** [comment]
For those who are facing this problem, follow the docs and you will not face this problem: http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

The issue will happen if the following code is present in your `settings.py`
```
# remove this and solve your problems!!!
import djcelery
djcelery.setup_loader()
```
