### ISSUE TITLE
djcelerymon - where does it live, how to create superuser?

### ISSUE THREAD

**Issue by anentropic** [celery/django-celery#159]
When I run `djcelerymon 8082` I see:

```
Django version 1.4, using settings '__default_settings__'
Development server is running at http://127.0.0.1:8082/
Quit the server with CONTROL-C.
Stale pidfile exists. Removing it.
[2012-07-25 10:56:58,752: INFO/MainProcess] -> evcam: Taking snapshots with djcelery.snapshot.Camera (every 1.0 secs.)
```

This is different to the `Django version 1.2.1, using settings 'celeryconfig'` shown in the docs. It also indicates it's using the Django 1.4 install from my system default Python rather than the Django 1.3.1 I have installed in my currently active virtualenv.

My problem is when it prompted me to create a superuser on first run I made a typo and hit `ctrl+c` to quit. Now I don't know what path to run the `./manage.py createsuperuser` command at to add it to the djcelerymon db.

The docs say I should have created a `celeryconfig.py` containing the db details (I didn't) and it will have created a sqlite db called `djcelerymon.db` but I can't find either of those files.

The djcelerymon server gets up and running and I can view it in the browser but can't login because I stuffed up creating my superuser.

Also, `ctrl+c` to quit the djcelerymon server doesn't work, I have to close the terminal window.

I'm on Ubuntu 12.04.

**Comment by saadqc** [comment]
@ask : hi, i have tried running celery with flask with dynamically adding/removing periodic tasks, but all in vain. Do you have any suggestion about using dynamic periodic celery tasks with flask only? and about djcelerymon, i cant find any proper method to run it, any help?
