### ISSUE TITLE
Celery 3.0.9 AttributeError: 'NoneType' object has no attribute 'conf'

### ISSUE THREAD

**Issue by trent** [celery/django-celery#185]
I am getting the following error after installing Celery==3.0.9 and trying to run ./manage.py celery worker

```
...
/local.py", line 169, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'NoneType' object has no attribute 'conf'
```

**Comment by sikendermd** [comment]
Hi all, 

I am using oracle-soa-plugin-1.3.1.xldp plugin and when i try to run sun soaDeploy.py and it shows me the attribute error.

runScriptFromDaemon("/tmp/ot-20151002T004427254/soaDeploy.py")
Disconnected from weblogic server: AdminServer
Processing [HelloWorld]
Traceback (most recent call last):
File "/tmp/ot-20151002T004428123/daemon.py", line 350, in ?
exec command
File "<string>", line 1, in ?
File "/tmp/ot-20151002T004428123/daemon.py", line 277, in runScriptFromDaemon
execfile(scriptPath)
File "/tmp/ot-20151002T004427254/soaDeploy.py", line 497, in ?
managedServerUrl="t3://"+deployed.container.host.address+":"+str(deployed.container.port)
AttributeError: 'NoneType' object has no attribute 'address'



Could anyone help me how to avoid this error please.
