### ISSUE TITLE
Task cleanup takes forever in MySQL

### ISSUE THREAD

**Issue by kjoconnor** [celery/django-celery#202]
We have millions of rows entered into `celery_taskmeta` per day, and then when the cleanup tasks run the queries take a very very long time.  Firstly, is there a reason to update tombstones that are about to be deleted in the next line of code to be hidden?  To hide them from the application while the DELETE is taking place?  This takes a long time, mostly because there's no index on `date_done`.  If the hiding is necessary, maybe there should be an index there?

I understand the DELETE will just take a long time if you have that many results, but maybe do it in chunks to prevent locking problems?

**Comment by auvipy** [comment]
@kjoconnor is this problem still exists? if not then we could close this issue.

**Comment by kjoconnor** [comment]
I'm not using celery anymore at the moment, so I'll close for now. Thanks!
