### ISSUE TITLE
"astimezone() cannot be applied to a naive datetime" when adding periodictask

### ISSUE THREAD

**Issue by ggendre** [celery/django-celery#239]
Hi,

I recently updated my whole stack to the latest versions of django, celery and django-celery.
To update my database I just deleted all djcelery related tables before installing packages.

When I add a new periodictask with a "crontab" entry in the django admin (admin/djcelery/periodictask), I have this issue :
    Exception Type: ValueError at /admin/djcelery/periodictask/add/
    Exception Value: astimezone() cannot be applied to a naive datetime

here is my stack :
Django==1.5
celery==3.0.17
django-celery==3.0.11
django-celery-with-redis==3.0
redis==2.7.2

I tryed to set USE_TZ to False in the django settings with no success.

Here is the end of the error trace :

```
File "/home/dotcloud/env/lib/python2.6/site-packages/django/dispatch/dispatcher.py" in send
  170.             response = receiver(signal=self, sender=sender, **named)
File "/home/dotcloud/env/lib/python2.6/site-packages/djcelery/models.py" in changed
  179.                                          defaults={"last_update": now()})
File "/home/dotcloud/env/lib/python2.6/site-packages/djcelery/utils.py" in now
  65.         return timezone.localtime(timezone.now())
File "/home/dotcloud/env/lib/python2.6/site-packages/django/utils/timezone.py" in localtime
  237.     value = value.astimezone(timezone)

Exception Type: ValueError at /admin/djcelery/periodictask/add/
Exception Value: astimezone() cannot be applied to a naive datetime
```

I'm also running PostgresSQL as my main database (9.0.4).
I know Postgres has a special DB type for TZ datetimes, I just checked and it seems to be alright ("timestamp with time zone" everywhere).

any clue?

**Comment by yeago** [comment]
I'm seeing this in 3.1.16
