### ISSUE TITLE
celerybeat is sending a task immediately after its assigning to another crontab

### ISSUE THREAD

**Issue by andreiko** [celery/django-celery#264]
I'm experiencing the following problem: when I'm changing a PeriodicTask from one crontab to another there is a possibility of immediate sending that task to queue by celerybeat.

Here is my setup that reproduces the problem:

Relevant settings:

``` python
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
TIME_ZONE = 'Europe/Moscow'
USE_TZ = True
```

Scheduling the task:

``` python
t = timezone.now() + timedelta(minutes=5)
t_local = timezone.localtime(t)

crontab = CrontabSchedule.objects.create(
    minute=t_local.minute,
    hour=t_local.hour,
    day_of_week='*',
    day_of_month='*',
    month_of_year='*',
)

PeriodicTask.objects.create(
    name='dummy',
    task='beatme.main.tasks.dummy',
    crontab=crontab,
    last_run_at=t - timedelta(days=1),
    total_run_count=1
)
```

At this point we have a task that should start every day at a specific time with `last_run_at` set to a time it should have been executed yesterday.
Let's start celerybeat and see that task is going to execute in about 4-5 minutes just as expected.

Now we create another crontab and assign it to our task:

``` python
task = PeriodicTask.objects.get(task='beatme.main.tasks.dummy')

t = timezone.now() + timedelta(hours=10)
tn_local = timezone.localtime(t)

crontab = CrontabSchedule.objects.create(
    minute=tn_local.minute,
    hour=tn_local.hour,
    day_of_week='*',
    day_of_month='*',
    month_of_year='*',
)

task.crontab = crontab
task.save()
```

I would expect celerybeat to send this task in about 10 hours, but it is being sent right on the next tick AND in 10 hours.

This is an unexpected behaviour for me if not a bug.

A quick fix for this is to attach pre_save signal that will clear `last_run_at` if crontab_id is changed.

All latest stable versions of django/celery/kombu/billiard etc were used during this test.

**Comment by jdxin0** [comment]
Same problem as @andreiko  in multiple circumstances.
PeriodicTask execute immediately.
1. change tasks. (change cron, change name, change arguments, change queue)
2. disable for one execution. (disable before cron execution time and enable after it)
