### ISSUE TITLE
Some tasks stuck on RECEIVED status.

### ISSUE THREAD

**Issue by javrasya** [celery/django-celery#310]
I have a task that create many sub tasks as group. Most of them is running properly. But a few of them stucks on RECEIVED status. Is this some kind of bug in celery or is there a solution for this?  
##### CELERY CONFIG

BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis"
CELERY_REDIS_HOST = "localhost"
CELERY_REDIS_PORT = 6379
CELERY_REDIS_DB = 0
CELERY_TIMEZONE = TIME_ZONE
CELERY_SEND_TASK_ERROR_EMAILS = True
CELERYD_LOG_FILE = 'logs/celery.log'
CELERYD_LOG_LEVEL = 'INFO'

Here is my celery runner;
python manage.py celery worker -B --soft-time-limit=10800 --concurrency=25

My task;

class ScheduledConfigProcessingDetectorTask(PeriodicTask):
    run_every = crontab() #Execute every minute
    max_retries = 1

```
def run(self, **kwargs):

    logger = self.get_logger(**kwargs)
    logger.info('Config processor scheduler task is started...')

    config_reader = RedisConfigReader(settings.CELERY_REDIS_HOST, settings.CELERY_REDIS_PORT,
                                      settings.CELERY_REDIS_DB)
    # processor_executor = PreProcessorExecutor()

    #change redis key for processing
    config_dict = config_reader.read_hash()
    for key in config_dict.keys():
        RedisUtil.rename(key, 'processing-%s' % key)
    try:
        for key, hkeys in config_dict.iteritems():

            uuid = key.split('_')[-1]

            sub_task_list = []
            for i, hkey in enumerate(hkeys):
                logger.info("Config with key '%s' is processing now." % (str(key)))
                sub_task_list.append(ProcessorTask().subtask(args=(uuid, key, hkey, len(hkeys))))
            job = group(sub_task_list)
            task_set = job.apply_async()

            while task_set.waiting():
                sleep(10)

            logger.info("Config with key '%s' is processed." % (str(key)))

            try:
                Task.objects.get(uuid=uuid, state=TASK_STATE_FAILURE)
                RedisUtil.rename('processing-%s' % key, 'error-%s' % key)
            except Task.DoesNotExist:
                #Success case
                config_reader.rs.delete('processing-%s' % key)
                logger.info("Processed config with key '%s' and  and deleted from redis" % (str(key)))
    except SoftTimeLimitExceeded, exception:
        logger.exception(exception)
        RedisUtil.rename('processing-%s' % key, 'error-%s' % key)
```

 And sub task

class ProcessorTask(Task):
    max_retries = 1

```
def run(self, uuid, key, hkey, total, **kwargs):

    logger.info('++++ Config processor task is started for key %s...' % (key))
    processor = PreProcessorExecutor()

    try:
        processing_key = 'processing-%s' % key

        json = RedisUtil.hget(processing_key, hkey)
        processor.execute(key, json)
        hkeys = RedisUtil.hkeys(processing_key)
        index = total - len(hkeys)
        logger.info('---- Config processor task is executed for key %s... (%s/%s)' % (key, index + 1, total))
        RedisUtil.hdelete(processing_key, hkey)
    except Exception as exception:
        logger.exception(exception)
```

**Comment by rudeb0t** [comment]
Sorry for posting on a closed issue, but I thought I'd post an update about this. We have been in the process of moving to new data centers and this issue seems to be much more pronounced now because of higher latency between our broker and our workers. After a bit of searching I think the solution is to add `--without-gossip --without-mingle --without-heartbeat -Ofair` to the Celery worker command line. This disables gossip, mingle, and heartbeat for our workers and as a result it sidesteps the issue entirely. The `-Ofair` option seems to solve the issue of some of our tasks that seem to be hanging because they are doing asynchronous HTTP transfers using the Python requests library. The workers running these command line options are currently being monitored to see if the issue continues to exist. I will post another update here in a few days.

**Comment by rosenhagen** [comment]
@rudeb0t the "-0fair" hint saved my week

**Comment by rudeb0t** [comment]
Final update on this issue. We have been running with those options and we have not had a single lockup on our workers ever since.
