### ISSUE TITLE
celerybeat stuck on starting

### ISSUE THREAD

**Issue by segalle** [celery/django-celery#313]
Hi there!

when i lunch celery beat i get the following output:

[localhost] local: celery beat
celery beat v3.1.9 (Cipater) is starting.
__    -    ... __   -        _
Configuration ->
    . broker -> amqp://guest@localhost:5672//
    . loader -> celery.loaders.default.Loader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> now (0s)
[2014-03-06 17:11:29,052: INFO/MainProcess] beat: Starting...

and that's it... it stays like that :(

**Comment by rehabshahzadi** [comment]
sir i am also getting the same error . Please help me.. what does that mean ""also i miss-referenced the CELERYBEAT_SCHEDULE to the correct file!"""

**Comment by oDoraemon** [comment]
@rehabshahzadi the same error.
I use the celery 3.1.25 under Windows. The debug info show no Current Schedule, and the beat process tick 5 mins to wait for next wake up. I manually add a schedule to the beat.py, make current schedule not empty, but still stuck on starting.
![image](https://user-images.githubusercontent.com/7870718/44903186-72c6aa00-ad3e-11e8-9721-0fb164b442d1.png)

My configuration and reference should be right, as it works pretty well under linux.
And I upgrade celery to 4.2.1, the beat process just work fine. But got another issue https://github.com/celery/celery/issues/3196

**Comment by mikoumed** [comment]
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
without the underscore between CELERY and BEAT ;)

**Comment by berzi** [comment]
Hi, I'm having this problem too. I'm *NOT* using the old django_celery_beat so the scheduler mentioned above is not available to me. This is the output I'm having with debug flag enabled:
```
celery beat v4.4.0 (cliffs) is starting.
__    -    ... __   -        _
LocalTime -> 2020-03-13 11:39:32
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%DEBUG
    . maxinterval -> 5.00 minutes (300s)
[2020-03-13 11:39:32,614: DEBUG/MainProcess] Setting default socket timeout to 30
[2020-03-13 11:39:32,614: INFO/MainProcess] beat: Starting...
[2020-03-13 11:39:32,697: DEBUG/MainProcess] Current schedule:
<ScheduleEntry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>
[2020-03-13 11:39:32,697: DEBUG/MainProcess] beat: Ticking with max interval->5.00 minutes
[2020-03-13 11:39:32,699: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
```
I have a debug task set up that should run every minute and just print() a message but it doesn't seem to get picked up.

**Comment by ziemowit141** [comment]
From: https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html
"Note that on_after_configure is sent after the app is set up, so tasks outside the module where the app is declared (e.g. in a tasks.py file located by celery.Celery.autodiscover_tasks()) must use a later signal, such as on_after_finalize."

Check whether you are using a correct signal, that might help :3

**Comment by Emmanuel-Aggrey** [comment]
> CELERYBEAT_SCHEDULE

yes the solved my problem it is

**`CELERYBEAT_SCHEDULE = 'django_celery_beat.schedulers:DatabaseScheduler'**

NOT

 **CELERY_BEAT_SCHEDULE = 'django_celery_beat.schedulers:DatabaseScheduler'**

`
