### ISSUE TITLE
OperationalError: (2006, 'MySQL server has gone away')

### ISSUE THREAD

**Issue by abhijo89** [celery/django-celery#359]
When ever i restart my MySql celeryd and celerycam throw OperationalError: (2006, 'MySQL server has gone away') .

```
    Traceback (most recent call last):
      File "/home/webapp/webapp/../vendor/djcelery/schedulers.py", line 204, in sync
        with commit_on_success():
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/home/webapp/webapp/../vendor/djcelery/db.py", line 56, in commit_on_success
        with transaction.atomic(using):
      File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 280, in __enter__
        connection.set_autocommit(False)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 333, in set_autocommit
        self._set_autocommit(autocommit)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 460, in _set_autocommit
        self.connection.autocommit(autocommit)
    OperationalError: (2006, 'MySQL server has gone away')
```

Is it a bug ?

**Comment by adriaant** [comment]
Lots of helpful stuff you can find via Google:
https://www.google.com/search?client=safari&rls=en&q=celeryd+MySQL+server+has+gone+away&ie=UTF-8&oe=UTF-8

It might be better to use something else as broker backend, e.g. RabbitMQ or Redis.

**Comment by trunneml** [comment]
Hi, we are using django-celery with redis as broker and result backend and getting the same error as @abhijo89  on a mysql restart or fail-over-switch. So it isn't a brocker or result backend problem. I think it is related to the scheduler.

**Comment by trunneml** [comment]
Hi, I found the problem that we had in the DatabaseScheduler. It does not create a new connection when the old one is broken. The patch above fixes the problem for me.

**Comment by chrono** [comment]
Had a similar issue, when we did an RDS failover. Broker backend is RabbitMQ, but scheduler is

```
OperationalError
Root Cause
(2006, 'MySQL server has gone away')
Stacktrace (most recent call last):

  File "djcelery/schedulers.py", line 176, in schedule_changed
    transaction.commit()
  File "django/db/transaction.py", line 139, in commit
    get_connection(using).commit()
  File "django/db/backends/__init__.py", line 171, in commit
    self._commit()
  File "django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
  File "django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
  File "newrelic/hooks/database_dbapi2.py", line 71, in commit
    return self.__wrapped__.commit()
```

versions:
```
pip freeze|grep celer
celery==3.1.18
django-celery==3.1.1
```

**Comment by abhijo89** [comment]
:+1:

**Comment by arturataide** [comment]
I have exactly the same error? 
<code>pip freeze | grep celer
celery==3.1.5
django-celery==3.1.1
</code>
Which version corrects this bug?
Thanks, Artur

**Comment by arturataide** [comment]
I have exactly the same error. The worker retrieves the "2006, 'MySQL server has gone away'" and freezes. I've applied the fix #359 but this issue continues to happen. 
Any ideas on this?
Thanks

**Comment by vakorol** [comment]
This seems to be a problem with `Celery`, not `django-celery`. I have the same problem, although am not using `django-celery` at all. There is a ticket on this:
https://github.com/celery/celery/issues/2919

**Comment by arturataide** [comment]
Thanks @vakorol. I am upgradind my app and I think I will change my database from MySQL to PostgreSQL. I've made some tests and with PostgreSQL the error seems to disappear.

**Comment by brianmay** [comment]
I am not sure I entirely understand the circumstances of this bug ...

To me this sounds suspiciously like a Django/mysql bug. mysql will close the connection if it has been idle for more then X seconds (value is configurable), and the client is suppose to attempt another connection to the server if this happens. It sounds very much like Django isn't doing this however, and generating an error instead.

http://dev.mysql.com/doc/refman/5.7/en/gone-away.html

**Comment by chrono** [comment]
I think the issue is that the exception handling here: https://github.com/celery/django-celery/blob/v3.1.17/djcelery/schedulers.py#L183-L185 is too eager and catching an exception that it is not handling properly. Instead it logs it and pretends nothing happened.

A proper way would be to do one of these things:
 * handle it (reconnect)
 * don't catch it
 * catch, log, raise.

**Comment by samskeller** [comment]
Just adding that I still have this problem constantly. Every time I restart my celery workers, things look fine for a little bit but then I get a barrage of these errors ("MySQL server has gone away"). The errors eventually stop, though, and the celery workers will then work fine until they're restarted again. Anybody have any ideas? Thanks!

**Comment by arturataide** [comment]
@samskeller I haven't manage to solve this issue.. Like I said on 22 Dec 2015 I've migrated to PostgreSQL, and obviously MySQL errors stopped. This kind of issue has never happened again with my new configuration.

**Comment by revilwang** [comment]
I'm using celerybeat to periodically run tasks every mintue. The broker and result backend both are RabbitMQ, with celerybeat using the default scheduler. There are django DB queries in the task, but still ("MySQL server has gone away") exception starts to pop up in DB query after several hours.

**Comment by vakorol** [comment]
I can update, that this is not an issue of `django-celery` project. I encounter this with Django 1.8.13 and Celery 3.1.23, not using `django-celery` at all.
To get rid of the error, i force a 
```python
django.db.connection.close()
```
inside my Celery job _before_ starting a possibly-long-running process. Django then re-opens the connection on the nearest database request.
Another workaround can be implementing a decorator, that would attempt to execute a function and catch the "MySQL server has gone away" exception. If caught, then close the connection and try again. I use this approach to re-establish lost sftp connections, and i think this should work for reconnecting to MySQL.

**Comment by revilwang** [comment]
@vakorol Right, it's not an issue of `django-celery`. We use the same method as you described, to force a DB connection close. Seems the problem no longer appears.

**Comment by auvipy** [comment]
then the issue should be closed

**Comment by chrono** [comment]
Please take another look at this stacktrace. The issue mentioned in the original filing by @abhijo89 (with the showing `djcelery`) and also my stacktrace further up is definitely an issue in `django-celery`.

The issue mentioned by @vakorol is a different one and is relating to a mysql connection within a worker.

This issue is relating to the django-celery scheduler, and related to celerybeat, not a worker. This issue is not solved.

**Comment by auvipy** [comment]
with the hope of getting this fixed, i'm re-opening it. if anyone could fix then please send a PR

**Comment by chrono** [comment]
![gif of steps to reproduce](https://s3.amazonaws.com/f.cl.ly/items/1H2U1J170n2k2B0x0U1l/Screen%20Recording%202016-06-22%20at%2004.11%20PM.gif?v=1a9b7255)

How to reproduce:

* Start celerybeat with djcelery `DatabaseScheduler`
* Cut connection to mysql
* reestablish connection to mysql

The database scheduler keeps spamming errors and does not recover from the outage or exit.

**Comment by rossigee** [comment]
In case it helps anyone else, one workaround for this is to disable Django's persistent connections by setting 'CONN_MAX_AGE' to zero in the django settings.py file.

**Comment by tmacjx** [comment]
Same Question with @chrono. I have add  setting 'CONN_MAX_AGE' to zero in the django settings.py file. Looked Fine now.

**Comment by tmacjx** [comment]
Still Exist when my project run a few days. Same Question with @chrono.  
Django (1.7)
django-celery (3.1.17)
Should I up upgrade edition?

**Comment by auvipy** [comment]
its solve with latest release

**Comment by newearthmartin** [comment]
Hi everyone

Does `CONN_MAX_AGE` also work for celery tasks? As it says that it will close connections after each _request_.

Also, has anyone experimented with [CONN_HEALTH_CHECKS](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-CONN_HEALTH_CHECKS)? I'm wondering if it's better to set `CONN_MAX_AGE = 0` or `CONN_MAX_AGE = None` and `CONN_HEALTH_CHECKS = True`.

I'm generally wary of these settings as they also impact requests and I have far fewer celery tasks than requests. There is a celery setting [database_short_lived_sessions](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-database_short_lived_sessions) that seems ideal but I have activated it and I'm still getting 2006 errors.

**Comment by famagusta** [comment]
I am still getting (2006, 'Server has gone away') with CONN_HEALTH_CHECKS set to True
Sometimes I get ProgrammingErrors as well. Not sure what this setting does if these 2 errors are still coming
