### ISSUE TITLE
Django 1.8 - There is no South database module 'south.db.sqlite3' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

### ISSUE THREAD

**Issue by papasax** [celery/django-celery#372]
I'm using Django-celery for the admin-schedule feature. Everything was working fine on Django 1.7.7. I just testes on Django 1.8.1 and got this error:
There is no South database module 'south.db.sqlite3' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

**Comment by papasax** [comment]
Oups!! I realized South was still installed in my environment. pip uninstall South just fixed my problems. Closing.

**Comment by MALANGBEIJING** [comment]
thanks, it works, but my problem of images do not show on PDF was solved by removing a slash from static of STATIC_ROOT = 'static/' directive, it was STATIC_ROOT = '/static/'.

**Comment by briansanchez** [comment]
thank you papasax

**Comment by VardhanHM** [comment]
I have got the same error. I have installed south inside my project and added it to installed_apps list in settings.py file. I get this error on running syncdb or "python manage.py schemamigration App_name --initial"

**Comment by adriaant** [comment]
Remove South from your installed apps. Django 1.7 and higher does not need South. See https://docs.djangoproject.com/en/dev/topics/migrations/#upgrading-from-south

**Comment by MC-HackerTech** [comment]
There is no South database module 'south.db.postgresql_psycopg2' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.
