### ISSUE TITLE
SubfieldBase pending deprecation (removed in Django 2.0)

### ISSUE THREAD

**Issue by thusoy** [celery/django-celery#377]
No rush yet, but just want to get this out here, SubfieldBase is being removed in favor of Field.from_db_value in django 2.0, thus [this line](https://github.com/celery/django-celery/blob/49e3fbbe9c08159014bb25e827376683af545d8d/djcelery/picklefield.py#L36) has to be modified.

**Comment by scarlac** [comment]
Support for SubfieldBase is set to end in Django 1.10 (currently we're on 1.9) and it is currently generating: `RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.` every time the development server (re)starts.

As far as I can tell, django-celery still depends on it, so this needs to be fixed for 1.10.

**Comment by sorter** [comment]
Since Django 1.10 is now released this should be fixed soonish as a matter of priority I think?

**Comment by vytisb** [comment]
This was fixed in v3.1.17.
