### ISSUE TITLE
Support django 1.7+ Appconfig.ready()

### ISSUE THREAD

**Issue by reinout** [celery/django-celery#382]
Django 1.7 has a new AppConfig object. One of the good things in there is the `ready()` method for actions that should be taken once Django has loaded. See https://docs.djangoproject.com/en/1.7/ref/applications/#django.apps.AppConfig.ready

This would be the perfect place for the `djcelery.setup_loader()` code that you now have to place in your settings file.

Or are there technical reasons why this wouldn't be possible?

Otherwise I could look if I could make a pull request for it.

**Comment by auvipy** [comment]
i think it's already fixed
