### ISSUE TITLE
New release with south_migrations

### ISSUE THREAD

**Issue by jdavisp3** [celery/django-celery#385]
Are there plans to cut a new release of this project that includes the changes to support Django 1.7 migrations?

**Comment by Kabal** [comment]
I would also like this :-)

**Comment by thedrow** [comment]
ping @ask

**Comment by richardxia** [comment]
I'd also love to see this.

**Comment by gregmuellegger** [comment]
:+1: +1

**Comment by lagesag** [comment]
:+1:

**Comment by AdrianLC** [comment]
Bump? It's been almost a year... I know that djcelery is mostly deprecated but still the database scheduler is useful and 1.7 is not even receiving security updates anymore.
