### ISSUE TITLE
problems with initial migration (py3 only)

### ISSUE THREAD

**Issue by agildehaus** [celery/django-celery#399]
To reproduce, simply:

```
pyvenv-3.5 venv
source venv/bin/activate
pip install django==1.8.6
pip install git+git://github.com/celery/django-celery.git@master
django-admin.py startproject demo
cd demo
<edit INSTALLED_APPS to include djcelery>
python manage.py makemigrations
```

Migrations are created when they should not be.  Additional makemigrations continually create migrations for djcelery.

This does not happen on python 2.7.

It happens on the current master branch and 3.1.17 on PyPi.

**Comment by MA-LUKUAN** [comment]
Same here, but the reason is Django 1.8.6
>Added a helpful error message when Django and South migrations exist in the same directory
https://code.djangoproject.com/ticket/25618

Back to 1.8.5, now works fine

**Comment by iho** [comment]
The same problem.

**Comment by themaxx75** [comment]
`./manage.py migrate djcelery --fake` is not stoping the 

```Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.```

Is there a solution for this?

**Comment by oTree-org** [comment]
I get the same issue with Py3, Django==1.8.8, and django-celery==3.1.17.

**Comment by nickfishman** [comment]
I'm also seeing the same issue with Python 3.5, Django 1.9.2, and django-celery 3.1.17.

The fix by @leonsim (https://github.com/leonsim/django-celery/commit/45a8ffb756f0514a11494ba9cc8ab808c91bdb4e) resolves the issue for me. Maybe we can get that merged into here?

**Comment by ask** [comment]
> On May 12, 2016, at 9:24 PM, Nick Fishman <notifications@github.com> wrote:
> 
> I'm also seeing the same issue with Python 3.5, Django 1.9.2, and django-celery 3.1.17.
> 
> The fix by @leonsim <https://github.com/leonsim> (leonsim@45a8ffb <https://github.com/leonsim/django-celery/commit/45a8ffb756f0514a11494ba9cc8ab808c91bdb4e>) resolves the issue for me. Maybe we can get that merged into here?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/celery/django-celery/issues/399#issuecomment-218949039>

It’s a real shame, but I have so little time that django-celery is not maintained at all.

If anyone wants to step up to prepare a release it would be really awesome, or just help triage issues.

I can give that person commit access and provide guidance as necessary!

-- 
Ask Solem
twitter.com/asksol | +1 (650) 575-5831

**Comment by auvipy** [comment]
@ask I will be happy to have the commit access. you could see my github activities and I have contributed on some django packages. I'm co maintaining drf-extensions now.

**Comment by ask** [comment]
@auvipy Thanks! I invited you, and you should have commit access as soon as you accept the invitation.  Tell me if you need anything else, twitter @asksol is usually a good way to reach me.

**Comment by auvipy** [comment]
@ask thanks. I will start work from tomorrow. I'm @auvipy py in tweeter too and knock you there if anything else is needed :)

**Comment by NULL-OPERATOR** [comment]
was there ever a fix to this?  :3

**Comment by agildehaus** [comment]
I believe so.

https://github.com/celery/django-celery/pull/405

**Comment by coredumperror** [comment]
Is a new release with this fix coming to PyPI any time soon? I would very much appreciate it.

**Comment by auvipy** [comment]
most likely yes.

**Comment by wicai** [comment]
Hi - sorry to bump this but I couldn't figure out from above what I should do about the fact that djcelery makes a migration every time I run makemigrations - is there currently a way to fix this?

**Comment by auvipy** [comment]
which version of djcelery are u using?

**Comment by wicai** [comment]
cement==2.8.2

**Comment by wicai** [comment]
oops sorry
celery==3.1.23

**Comment by auvipy** [comment]
can you try the master branch of django-celery?

**Comment by wicai** [comment]
How do I do that?  Just pip update?

**Comment by auvipy** [comment]
try this way as master branch is not yet in pypi: pip install git+git://github.com/celery/django-celery.git@master

**Comment by the-kid89** [comment]
any news on when this will make it into pypi?

**Comment by the-kid89** [comment]
any news on when this will make it into pypi?
