### ISSUE TITLE
Django 1.9 Result Backend Incompatibility

### ISSUE THREAD

**Issue by malefice** [celery/django-celery#407]
Attempting to use `CELERY_RESULT_BACKEND='djcelery.backends.cache:CacheBackend'` with Django 1.9 will cause the celery workers to fail with this error message:

`Message Error: Couldn't apply scheduled task Test: cannot import name 'get_cache'`

This is caused by Django 1.9 removing the `get_cache()` API in favor of `caches()` as stated in the [Django docs](https://docs.djangoproject.com/en/1.8/topics/cache/#django.core.cache.get_cache).

**Comment by brianmay** [comment]
I have a "fix" for this in #411. At least the tests pass anyway.

**Comment by vladir** [comment]
So is Django 1.9 already supported? Thanks in advance

**Comment by brianmay** [comment]
What do you mean by "supported"? This project appears to be dead. It does work if you apply the appropriate set of patches.
