### ISSUE TITLE
3.1.17 detects unmade migrations due to absolute import

### ISSUE THREAD

**Issue by jdzero** [celery/django-celery#409]
I am using djcelery 3.1.17 with Django 1.7.10 with Python 2.7.9 and deploying to Heroku.  I recently introduced a command to guard against permitting a build if any migrations are unmade.  While this runs fine on my dev machine and on Circle's run of "migrate," when it gets to Heroku it fails because of an incompatibility between absolute importing and the pickle field.  I suspect the placement of the third-party packages under the same project root (by Heroku) and the future import of absolute_import by the Django 1.10 migration may be the culprit.  I was able to solve this problem by using a relative import within the migration as follows:

Doing a relative import of the picklefield module (from .. import picklefield)
Replacing the three references to djcelery.picklefield

This allows the 1.7 migration framework to detect no changes since it now assesses the underlying field has not changed.  Appreciate your consideration of this and happy to throw a PR up if it/another approach will be accepted.

**Comment by jdzero** [comment]
Sorry maybe this was premature...looking more at master it looks like this may be addressed by the migration re-write that takes place there.  Any ETA on 3.2 getting released or is this project being abandoned?

**Comment by brianmay** [comment]
Looking at the lack of response to bugs like #342 and #411 I think this project is basically abandoned :-(

**Comment by Feuermurmel** [comment]
Would it help to just just add the automatically created migrations and submit them as a pull request? Then they could be integrated in a new release (e.g. 3.1.18). I could provide that pull request.

**Comment by brianmay** [comment]
@Feuermurmel have a look at the large list of pending merge requests already. Some of these merge requests are very simple too. I think somebody needs to take over the development of this project or fork it. Unfortunately I already have too many projects, I can't take on another one myself.

**Comment by auvipy** [comment]
try the 3.2.0 and hope that will work
