### ISSUE TITLE
Broken migrations using python 3.5 

### ISSUE THREAD

**Issue by spapanik** [celery/django-celery#414]
The projects continuously needs new migrations.

Steps to reproduce:
- pip install django celery django-celery
- django-admin startproject mysite
- add djcelery to installed apps
- ./manage.py migrate

from now on, all the time makemigrations produces a new migrations that just reorders the taskmeta fields.

**Comment by willhardy** [comment]
The choices for the status field comes from `ALL_STATES` which is an (unordered) set. Sorting this before creating `TASK_STATE_CHOICES` will mean that Django will always see the same ordering for the choices and won't feel the need to create a new migration.

**Comment by willhardy** [comment]
Note this affects Python 3.4+, because it's triggered by [PEP 456](https://www.python.org/dev/peps/pep-0456/)

**Comment by mbande** [comment]
any workaround suggestion ?

**Comment by spapanik** [comment]
As as workaround you can sort the TASK_STATE_CHOICES in djcelery/models.py

**Comment by apollo13** [comment]
This is fixed in c5c9a6f39271b87eec736cea8bbb413c55fdf050 -- but apparently it never got released.

**Comment by PavlinGergov** [comment]
Ping.
Any progress here? 
## Atm the super cool flow is:
* Step 1: `python manage.py makemigrations`
```
Migrations for 'djcelery':
  0123456789_auto_20160627_0725.py:
    - Alter field status on taskmeta
```
* Step 2: `python manage.py migrate`
```
Running migrations:
  Rendering model states... DONE
  Applying djcelery.0123456789_auto_20160627_0725... OK
```
* Step 3: `python manage.py runserver`
```
You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.
```
Go to *Step 1*.

**Comment by RadoRado** [comment]
I love recursion, but sometimes, this extra `djcelery` migration can be really cumbersome :( Is there someone who can accept PR with fix in this repository?

**Comment by apollo13** [comment]
@RadoRado As I wrote already, this is fixed, there is no need for a PR but just a new release, see the latest commits on master…

**Comment by PavlinGergov** [comment]
@apollo13 updated to the latest master: `pip install https://github.com/celery/django-celery/zipball/master`, got ```SubfieldBase has been deprecated.```

Applied this https://github.com/celery/django-celery/commit/c5c9a6f39271b87eec736cea8bbb413c55fdf050 locally in my virtualenv, worked as a charm. 

GL,
pceout

**Comment by auvipy** [comment]
there will be a new release in few weeks I hope.

**Comment by jmordkoff** [comment]
adding this to my settings file made it go away for now -- 

MIGRATION_MODULES = {
    'djcelery': None,
}
