### ISSUE TITLE
Django Admin

### ISSUE THREAD

**Issue by nikolaz111** [celery/django-celery#419]
The new documentation says this package is no longer needed. This app provides a powerful Django admin integration which is vital for my project. Is there a way to integrate celery to the Dajngo admin without using this package?

**Comment by auvipy** [comment]
well actually this project is still needed for django admin integration and use django as result backend. for using celery only you don't need it. docs need modification.

**Comment by malefice** [comment]
I also like to add that this package is vital in more ways than @nikolaz111 mentioned. Personally, I do not like how celery proposes that the schedule for periodic tasks be made. The way I see it schedules are written in Python code in the settings file.

When in production, I am not really comfortable letting members of support team (Tier 1/2) edit those files just so they can modify schedules. It is way better to give them limited access to the Django admin. Not to mention, you will need to restart the workers every time the settings will be modified using celery's proposed method.

Anyway, I would even go as far to say that this app is "recommended" and not something "only required if blah blah". On that note, I am very glad that to see that this project is not yet dead. :+1:

**Comment by auvipy** [comment]
this is not dead
