### ISSUE TITLE
make djcelery capture tasks args configurable

### ISSUE THREAD

**Issue by zhihuiFan** [celery/django-celery#421]
I used djcelery in my program. and I have something like this.

def handle(req):
   task_name.apply_async(args=(req.POST['username'], req.POST['password'], 'p1', 'p2'), queue='x')

The bad thing is djcelery stores/shows every user/password information in django admin/flower, this is not I want.  Can I avoid this?

**Comment by zhihuiFan** [comment]
this should be the cause.  since we used celerycam,  which stores the args.  Do we have a simply way to inject some user defined code to change this behavior in current implementation?

Thanks

**Comment by auvipy** [comment]
ask this to irc channel
