### ISSUE TITLE
djcelery 3.1.17 on django 1.9.5 generates new constant migration all the time

### ISSUE THREAD

**Issue by mnesterovych** [celery/django-celery#422]
Hello.
After switching to django 1.9.5, I've noticed that after each manage.py makemigrations run, new migration is generated for TaskMeta model.
Looks like issue sin choises for status field.
Now it corresponds to TASK_STATE_CHOICES = zip(states.ALL_STATES, states.ALL_STATES)
which is dynamic function call. So every model check, django thinks it's completely new and creates migration

**Comment by mnesterovych** [comment]
Looks like this happened cos, 1.9 does not support south migrations any more, and django migrator threat call of the zip function as new by default.

**Comment by nick-allen** [comment]
Looks to be fixed in recent commit

https://github.com/celery/django-celery/blob/c5c9a6f39271b87eec736cea8bbb413c55fdf050/djcelery/models.py#L21

**Comment by auvipy** [comment]
the master branch dropped support for south that means anything lesser then 1.7

**Comment by SebCorbin** [comment]
Okay so this seems fix in master, but not released, is there any way to use the last stable version with pip?

**Comment by auvipy** [comment]
yes.

pip install django-celery=={version you want}

**Comment by Pentusha** [comment]
@auvipy do you have access rights to make new release on pypi?

**Comment by auvipy** [comment]
no, but only some docs about release notes required for a new release

**Comment by SebCorbin** [comment]
From #460 it seems that @ask has access to pypi repository, I can provide some help if needed.
There have been no release for a year now and we have outstanding issues since 3.1.17.

Releasing a version would help triaging issue queue because lots of people tend to use the last one, instead of master. Examples are #404 #409 #414 and so on.

**Comment by RadoRado** [comment]
Everyone, there is a new `django-celery-results` repo - <https://github.com/celery/django-celery-results>

I guess it's migration time.

**Comment by themaxx75** [comment]
is `django-celery-results` a drop-in replacement?

**Comment by RadoRado** [comment]
@themaxx75 for latest versions of Django & Celery - yes.

For legacy projects, I guess you still have to use `djcelery`

**Comment by SebCorbin** [comment]
That does not solve this issue, AFAIC I'm using `django-celery` to manage tasks (along with task results) and this repo is not a drop-in replacement.

**Comment by RadoRado** [comment]
@SebCorbin what do you mean by "manage tasks and tasks results" ? From the django-admin?

**Comment by SebCorbin** [comment]
I currently use `CrontabSchedule` and `PeriodicTask` to allow users to set their own notification frequency. My bad: results are only kept in rabbitmq for now.

**Comment by RadoRado** [comment]
@auvipy cheers for the release :beers:

**Comment by SebCorbin** [comment]
Oh yeah! here's some ❤️ 
First step done, now https://pypi.python.org/pypi/django-celery? :)
