### ISSUE TITLE
How to run celery periodic task starting from specific date to some other date

### ISSUE THREAD

**Issue by nileshsutar** [celery/django-celery#425]
I want to run periodic task with some cron type scheduler with some fixed date range.
lets say I want to run task from 25 May 2016 to 30 Nov 2016 for an every hour.
Any example?

**Comment by Yash17Agrawal** [comment]
If i am not wrong ETA and EXPIRES are already present.
http://docs.celeryproject.org/en/latest/userguide/calling.html#eta-and-countdown
`tomorrow = datetime.utcnow() + timedelta(days=1)`
`add.apply_async((2, 2), eta=tomorrow)`

AND 
`add.apply_async((10, 10), kwargs, expires=datetime.now() + timedelta(days=1)`
