### ISSUE TITLE
wrong cron calculation * * * * *

### ISSUE THREAD

**Issue by Hinnack** [celery/django-celery#436]
I have a task decorator like this (every monday at 11):
@periodic_task(run_every=crontab(hour=11, day_of_week='mon'))

the __str__ method of CrontabSchedule calculates that to:
* 11 mon * *

which should be:
0 11 * * mon

or should it not be cron compatible?

**Comment by PMickael** [comment]
That's ok, it's not used with system crontab, it's just the same representation/usage and the repr is :
```python
CRON_REPR = """\
<crontab: {0._orig_minute} {0._orig_hour} {0._orig_day_of_week} \
{0._orig_day_of_month} {0._orig_month_of_year} (m/h/d/dM/MY)>\
"""
```
Also @period_task is deprecated.

**Comment by ask** [comment]
It's cron compatible, but the default minute in this API is `*`.  You currently have "Execute every minute during the 11th hour every monday", when you probably want to specify `crontab(minute=0, hour=11, day_of_week='mon')`
