### ISSUE TITLE
Clarify supported Django versions

### ISSUE THREAD

**Issue by vytisb** [celery/django-celery#442]
It would helpful to specify the versions of Django that we aim to support. There's some old compatibility code that could be removed.

Judging by the removal of south migrations, I assume it's >=1.7. 
Tox configuration file specifies 1.7-1.9.
Proposed Travis configuration (#438) specifies 1.8-1.10.

Personally, I think we should aim for 1.8-1.10, since 1.7 upstream support has ended and 1.8 is an LTS.

**Comment by auvipy** [comment]
yess thats the target.
