### ISSUE TITLE
Management commands fail on Django 1.10

### ISSUE THREAD

**Issue by vytisb** [celery/django-celery#447]
Management commands fail due to incompatible argument parsers.

Django 1.10 dropped support for `optparse` in management commands (deprecated since 1.8) in favor of `argparse`.

Celery is using `optparse`.

**Comment by themaxx75** [comment]
Any workaround in the meantime?

**Comment by akshaysharma096** [comment]
Any particlular fix for the problem

**Comment by onegreyonewhite** [comment]
Hi, everyone!
When changes in master branch will be released to pip?

**Comment by d33tah** [comment]
Ping @celery @vytisb. Django 1.9 ended mainstream support as of August 1, 2016.

**Comment by EdwinRor** [comment]
Had lots of problems with django 1.10. pip install django==1.9.2 fixed all my celery django problems.

**Comment by d33tah** [comment]
@EdwinRor: that's not really a long-term solution :p

**Comment by bgroff** [comment]
Also if you are going to use django 1.9 you should use the latest version, which as of today is 1.9.11

**Comment by muminoff** [comment]
See https://github.com/celery/django-celery/issues/457#issuecomment-261177413

**Comment by davidhalter** [comment]
With `django-celery==3.2.1` this issue was fixed and you can close this issue.

**Comment by auvipy** [comment]
thanx

**Comment by arvindadari38** [comment]
thank you. That worked
