### ISSUE TITLE
New release for Django >= 1.10 ?

### ISSUE THREAD

**Issue by Alir3z4** [celery/django-celery#460]
The latest version `3.1.17` is not compatible with Django >= 1.10
I see there're some bugs that have been fixed on the master branch.

Is there any ETA for new release ?

**Comment by auvipy** [comment]
you can use master branch using pip

**Comment by listingmirror** [comment]
@auvipy Would still be nice to cut a release, seems a lot of people wanting to use this with 1.10 still.

**Comment by auvipy** [comment]
yeah that's true. will try ASAP

**Comment by ask** [comment]
@auvipy If you prepare the release with a Changelog then I can give you access to PyPI and the PGP key.

Remember to update the version number in `__init__`, `docs/introduction.rst` and `README.rst` :)

**Comment by auvipy** [comment]
OK will try to complete today

**Comment by themaxx75** [comment]
Just wanted to say that I really appreciate this. 
Thanks everyone for all your work! Looking forward to the new release.

**Comment by listingmirror** [comment]
@auvipy anything I can do to help get this ready for release?

**Comment by Stranger6667** [comment]
Hello, any updates?

**Comment by fission6** [comment]
when will this be on pypi?

**Comment by auvipy** [comment]
branch cut https://github.com/celery/django-celery/releases/tag/v3.2.0 

only pushing to PyPI remain I guess
