### ISSUE TITLE
Celery Beat ignores a task's options dictionary

### ISSUE THREAD

**Issue by emperorcezar** [celery/django-celery#463]
Say I decorate a task and pass values to it using the options dictionary
`@shared_task(options={'queue': 'low-default'})`. Here the queue is set, but other options can be set also. Djcelery will ignore these options when kicking off the task.

A possible solution is to just set a default to the options like so in the scheduler **init**

```
self.options = {'queue': model.queue or task_options.get('queue'),
                        'exchange': model.exchange or task_options.get('exchange'),
                        'routing_key': model.routing_key or task_options.get('routing_key'),
                        'expires': model.expires or task_options.get('expires')}
```

I've been doing that with success.

If that looks good, I'll roll up a PR.

**Comment by auvipy** [comment]
which options do you need should be allowed and which kept off?

**Comment by emperorcezar** [comment]
Seemed to me the same options that it can pull from the model. This allows the model to override the options in the code.

**Comment by as3445** [comment]
This issue was fixed in https://github.com/celery/django-celery-beat/pull/34 in the django-celery-beats repo, is this issue still applicable to this repo in particular? @emperorcezar

**Comment by emperorcezar** [comment]
Don't think so. I'll close.
