### ISSUE TITLE
Should the webhook views in this repo be used?

### ISSUE THREAD

**Issue by codersquid** [celery/django-celery#469]
The [webhook docs](http://docs.celeryproject.org/en/latest/userguide/remote-tasks.html) show that djcelery views are used in the webhooks example for Django projects. If this repo is to be deprecated, then is it expected that users should not use these views and instead write their own?

**Comment by auvipy** [comment]
ask questions to irc channels

**Comment by codersquid** [comment]
Update the readme to document where questions should go.
