### ISSUE TITLE
Celery ignores schedule on close DB connection and restart

### ISSUE THREAD

**Issue by gmixo** [celery/django-celery#478]
Currently I use a celery for manage some tasks and meet some strange behavior.
I use postgres DB and start restore db from dump. My restore script at first closes all db connections and than drop db, do restore, etc. So celery connection was also closed. after that I restarted celery and it start execute scheduled tasks with ignore currently used schedule. Is I'm do anything wrong? Is celery don't like this hard disconnects?
If I do simply celery restart it looks ok and all is good.
Any help please!

**Comment by vytisb** [comment]
Database scheduler stores last execution time for each task in the database. When you restore the database, you get the last execution times that were at the moment of backup. I suppose, for some tasks enough time has passed between backup and restore that there is a "missed" execution. When you launch the scheduler, it sees that it's late and runs the task(s) right away.

If you want to avoid this, I guess you'd need to clear schedule from the database before running the scheduler.

**Comment by gmixo** [comment]
Excellent! thanks for answer!
