### ISSUE TITLE
Not supported django 1.10.x yet?

### ISSUE THREAD

**Issue by xukaizai** [celery/django-celery#483]
cmd: python manage.py celery worker -l info
startup failed:
`AttributeError: type object 'BaseCommand' has no attribute 'option_list'`

My info.
Python 2.7.10
celery 3.1.24
django-celery 3.1.17

**Comment by zeonn** [comment]
and for python 3.5 too

**Comment by azmeuk** [comment]
This has been fixed in #485. I suppose a new release is imminent.
