### ISSUE TITLE
Celery 4.0 and the future of django-celery project

### ISSUE THREAD

**Issue by malefice** [celery/django-celery#493]
Hi guys! So celery v4.0 has been released, and according to the new docs, there are dedicated [Django extensions](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#extensions) that seem to overlap with, if not deprecate, this project for newer versions of Python and Django.

Will this be the direction moving forward? Specifically the `django-celery` package should only be used if one is using Django<=1.8 with Celery<=3.1, and one should update libraries whenever possible.

**Comment by d33tah** [comment]
Ping top contributors: @ask @vytisb @auvipy @ionelmc @diegueus9 @jasonbaker

**Comment by ionelmc** [comment]
Which features of django-celery do you care about? There are almost no features not included in base celery/kombu. One notable feature is the monitor that records events in Django models, but I'd argue it's better and easy enough to implement your own monitor if you want to save event stuff in a table (I have found that the hard way, by ~~suffering~~using django-celery 😀).

**Comment by ask** [comment]
The idea was for the new extensions to replace django-celery entirely.

That django-celery is optional was really confusing users in Celery 3.1, and it seems a logical next step.

The only thing django-celery provides that is not available anywhere else is now (AFAIR):

- The Django Admin monitor.

Writing the events to the database all the time is a suboptimal solution so I'd rather see Flower being embedded in the Django-Admin (fully, or in an iframe maybe).

- The views in djcelery/views.py

   These are super old examples that I wrote, I'm not sure if anyone is using them.
   Maybe Jobtastic could take over this part.



The extensions are also better than in django-celery in some ways, cleaning up some cruft that was there for backwards compatibility, like the django-celery-result extension no longer uses PickleField to store results :tada:

**Comment by malefice** [comment]
Actually the feature that matters most to me is the ability to create periodic tasks via the admin interface. For many use cases, specifying the schedules in `settings.py` is sufficient.

However, in my use case, where the same concept of a particular task is shared across different clients, departments, or organizations, but each has a different schedule and/or has different args/kwargs passed into the same task function, and said schedules may change on a whim, manually editing the `settings.py` file is not sustainable.

Moreover, I can sleep more soundly if I give support personnel limited access to the admin interface to edit those tasks VS giving them shell access and let them edit production code. IMO, that alone is enough to make this a must-have package instead of an optional one. Kind of like pytz is to Django.

Anyway, thanks for the clarification! At least now we know that deprecation of this project is indeed the direction.

**Comment by evgenyfadeev** [comment]
I've installed django-celery==3.1.17 and it brought celery v 4 as dependency, which is apparently incompatible. Why not limit compatible dependency versions from above to make sure that pip installed apps work smoothly?

**Comment by malefice** [comment]
The latest release still does not have the fix. You can take a look at PR #486. Only the master branch has this fix.

**Comment by kanemra** [comment]
@malefice 

> Actually the feature that matters most to me is the ability to create periodic tasks via the admin interface.

http://django-celery-beat.readthedocs.io/en/latest/

**Comment by malefice** [comment]
@kanemra , I am aware that package exists. I even posted links on my first post and I said in another post that I will start using the new packages when I have a chance. I opened this issue to get some clarifications on the direction.

**Comment by iho** [comment]
@kanemra this package do not work. lol

**Comment by listingmirror** [comment]
@ask  Flower is pretty terrible, not sure it should be the replacement for anything. maybe I am "unique" in that I autoscale my workers up and down a fair bit, but flower quickly becomes a giant wall of deleted machines and you are unable to parse anything. I now exclusively use the rabbit-mq GUI if I want a quick eyeball of queue depth or burn rate.

**Comment by arcivanov** [comment]
I have restored Django and SQLAlchemy in Kombu backends for Python 3 and will be maintaining them, since I need Django and Celery 4.

See [karellen-kombu-ext](https://github.com/karellen/karellen-kombu-ext)

**Comment by erik-sn** [comment]
Just to give my use case:

- We use Windows for Celery which is not supported in v4, so we have to stick with 3.1. We have tried to get 4 to work but unsuccessfully.
- Due to this we cannot use the dedicated django extensions which aren't compatible with 3.1.
- The main benefit is the admin interface and scheduling periodic tasks through it

Unless I have missed something of course, I think we are frozen on this one until we can manage to migrate our celery to a linux serer.

**Comment by auvipy** [comment]
@arcivanov using django n sqlalchemy as message transport is a very bad idea. these are ok as result backend

**Comment by arcivanov** [comment]
@auvipy It is a very good idea if I need my application to run off of sqlite in single process self-contained application in the same manner as distributed off of PG and RabbitMQ. I'm not suggesting this by any means for production distributed environment, of course, but with an addition of [SQLite update hook](https://www.sqlite.org/c3ref/update_hook.html) to remove queue polling this will provide an excellent pure-python deployment for single-instance running.

**Comment by auvipy** [comment]
@arcivanov I understand what you meant
