### ISSUE TITLE
Bug? Task run upon saving it even if time is in the past

### ISSUE THREAD

**Issue by km-pg** [celery/django-celery#495]
I'm not sure if this is intended behavior or not, but it bit us.

Steps to reproduce:

- create a periodic task with a crontab for a minute in the future (for example: 30 10 * * *)
- wait for it to send
- wait a minute (for 31 to pass)
- change the time for 1 minute past the initial minute set (example: 31 10 * * *)

Even though this minute (31) has already past, the task is still sent.

Is this a bug?

**Comment by auvipy** [comment]
to ask this type of question please go to the celery irc channel
