### ISSUE TITLE
version 3.2.0 not available in PyPi

### ISSUE THREAD

**Issue by vedarthk** [celery/django-celery#501]
Getting this error while installing `django-celery==3.2.0`

```
Could not find a version that satisfies the requirement django-celery==3.2.0 (from -r requirements_django_upgrade.txt (line 12)) (from versions: 2.0.0, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.7, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 3.0.0, 3.0.1, 3.0.4, 3.0.6, 3.0.9, 3.0.10, 3.0.11, 3.0.17, 3.0.21, 3.0.23, 3.1.0, 3.1.1, 3.1.9, 3.1.10, 3.1.15, 3.1.16, 3.1.17)
```

**Comment by auvipy** [comment]
yes please try from github as not yet pushed to pypi. @ask could you push the package? or want me to publish?

**Comment by charlex** [comment]
+1

**Comment by cdelguercio** [comment]
+1

**Comment by auvipy** [comment]
gentle pin to @ask

**Comment by nikokio** [comment]
+1

Additionally, there is a bug in the djcelery/__init__.py:

VERSION = (3, 2, 0,)

instead of:

VERSION = (3, 2, 0)

note the last comma.

This result in pip to install version 3.2.0- and making a lot of trouble :)

**Comment by auvipy** [comment]
https://github.com/celery/django-celery/tree/v3.2.1

**Comment by vedarthk** [comment]
@auvipy also please can you upload the release on PyPi ?

**Comment by auvipy** [comment]
I can't only @ask can :dagger:

**Comment by nikokio** [comment]
Unfortunately... and @ask seems to have been "devnapped" ;)

**Comment by Henner** [comment]
+1

**Comment by tomasgarzon** [comment]
+1

**Comment by AlexvEck** [comment]
+1

**Comment by maryokhin** [comment]
yes, please, it's a shame that only one button press remains and it isn't pressed

**Comment by palmchou** [comment]
@ask . Please help.

**Comment by ask** [comment]
3.2.1 is on PyPI, but I had to regenerate the tag as the tag was inconsistent with the version information.

I'm a single dad with a day job and 10k unread emails.  Open source work does not pay bills, or impress women, so need to be notified the tag was created, or it's going to take some time before I notice :)

**Comment by maryokhin** [comment]
thanks @ask, it really is a shame open source does not impress women

**Comment by nikokio** [comment]
@maryokhin Ah ah, true !

Thanks @ask ! Anyway, due to issue #507 it won't help me.

You shouldn't be the only pusher on such a big project such as celery. Any trusted person to share the keys ?

**Comment by vedarthk** [comment]
Thanks @ask 👍
