### ISSUE TITLE
InconsistencyError

### ISSUE THREAD

**Issue by mingchunmao** [celery/django-celery#504]
InconsistencyError:
Cannot route message for exchange 'celery': Table empty or key no longer exists.
Probably the key ('_kombu.binding.celery') has been removed from the Redis database.

**Comment by auvipy** [comment]
versions?

**Comment by mingchunmao** [comment]
2.10.5

**Comment by auvipy** [comment]
try the latest versions

**Comment by mingchunmao** [comment]
I used the default .conf, now I set a password, if it doesn't work, then upgrade to the latest version

**Comment by mingchunmao** [comment]
This error occur every few hours before，now it seems to disappear.
