### ISSUE TITLE
ImportError: No module named south.db

### ISSUE THREAD

**Issue by sohamnavadiya** [celery/django-celery#505]
I updated django 1.7 to 1.9.12,
After updating it, I am getting below error stack.

```
 File "/home/abc/Documents/venv/upgrade_1_9/local/lib/python2.7/site-packages/djcelery/migrations/0001_initial.py", line 5, in <module>
    from south.db import db
ImportError: No module named south.db
```

I am using **django-celery==3.1.16**

How can I solve this error?
Thanks in advance.

**Comment by auvipy** [comment]
why you are still using south? django 1.7 has built in migrations. so south is removed

**Comment by sohamnavadiya** [comment]
I am not using south. I am getting this error from djcelery lib as you can see mentioned log.

**Comment by AnjaneyuluBatta505** [comment]
Upgrade django-celery to latest version (It fixed my problem)
