### ISSUE TITLE
Does django-celery support Django 1.11.1?

### ISSUE THREAD

**Issue by giordano91** [celery/django-celery#520]
Hi all,
in my application i'm using 

    Django 1.7
    Celery 3.1.17
    django-celery 3.1.16

I'd like upgrade all these components to the latest versions, this means 

    Django 1.11.1
    Celery 4.0.2
    django-celery 3.2.1

Reading the _django-celery_ documentation, I have noticed that it is compatible with Django 1.10, but I didn't find any information about Django 1.11.

Are there any news about Django 1.11.1 support? If yes, is it already planned a new release about that?

I'm doing a sort of investigation about Django and site-packages release notes before upgrade them, and this is the reason of this question.

Thanks in advanced

Best regards

**Comment by auvipy** [comment]
use django-celery-beat and django-celery-result instead of it unless your project is very much tightly integrated with it

**Comment by giordano91** [comment]
First of all thank you for the timely reply.
Do they (django-celery-beat and django-celery-result)  support Python 3.6? Because this is another requirements of my application.

**Comment by auvipy** [comment]
they should work AFAIK

**Comment by giordano91** [comment]
OK, thank you!
