### ISSUE TITLE
Celery worker freezes suddenly when trying to pass 200 tasks at a time

### ISSUE THREAD

**Issue by gauravt1** [celery/django-celery#521]
When I am trying to throw around 200 tasks to celery than worker will not respond, It just takes a single task and then freeze down. Although It's working fine with 150 tasks. I'm not understanding where I committed mistake.

I'm using the following packages - 

celery==3.1.20
django-redis==4.0.0
redis==2.10.5
websocket-client==0.35.0
django-celery==3.1.16
Django==1.8.4

the following are the celery values in settings.py - 

    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_ACCEPT_CONTENT = ['json', 'pickle']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_ACKS_LATE = True
    CELERY_CREATE_MISSING_QUEUES = True

    # Queues create later
    CELERY_DEFAULT_QUEUE = 'default'
    CELERY_QUEUES = (
        Queue('default', routing_key='default'),
        Queue('queue-engine', routing_key='queue-engine'),
        Queue('unready_state', routing_key='unready_state'),
    )
    CELERY_DEFAULT_EXCHANGE = 'default'
    CELERY_DEFAULT_ROUTING_KEY = 'default'
    CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
    CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
    CELERY_TIMEZONE = 'UTC'

here are production system specifications - 

Architecture:          x86_64
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
CPU family:            6
Stepping:              1
CPU MHz:               2300.050
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K

I have also raised a similar issue and I got reply that - Celery 4.0 has better control over Redis brokers.
But the existing django-celery which I am using is not compatible with Celery 4.0 So, do I need to remove django-celery? or Is there any alternative to fix it?

**Comment by auvipy** [comment]
update django-celery to 3.2.x with celery 3.x and for celery 4.x use django-celery-beat
