### ISSUE TITLE
Import Error: No module named timeutils

### ISSUE THREAD

**Issue by kanishkatn** [celery/django-celery#523]
Hi,

I am getting the following error when I try to run migrate in my django project. 

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
>     utility.execute()
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
>     django.setup()
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models()
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/djcelery/models.py", line 16, in <module>
>     from . import managers
>   File "/home/ubuntu/.virtualenvs/site/local/lib/python2.7/site-packages/djcelery/managers.py", line 18, in <module>
>     from celery.utils.timeutils import maybe_timedelta
> ImportError: No module named timeutils

These are the versions I am using
Celery: 3.1.23
django-celery: 3.2.1
Django: 1.11

I did come across the tickets with the same issue. They weren't addressing my versions. So, I had to create a new one. 

I want to know if there is a workaround for this. If not, what would be my best choice to get around the error without upgrading to celery 4.0.x ?

Cheers,
Kanishka

**Comment by georgepsarakis** [comment]
I think https://github.com/celery/django-celery/pull/524 will solve this issue.

**Comment by kanishkatn** [comment]
Thanks @georgepsarakis 

But I got it working by using these versions
celery==3.1.23
django-celery==3.1.17

**Comment by georgepsarakis** [comment]
Module `timeutils` was renamed in Celery version 4.0 .
