### ISSUE TITLE
django-celery 3.1.17 does not support latest celery

### ISSUE THREAD

**Issue by shimulch** [celery/django-celery#531]
django-celery v3.1.17 doesn't work with latest celery. When I have downgraded celery to v3.1.17 it works fine. 

In setup.py I see

```python
install_requires=[
     'celery>=3.1.15',
],
```
May be it needs to be adjusted to not go higher then 3.1.17 or something like that.

If that is the case, I would love to submit a PR.

**Comment by auvipy** [comment]
yes django celery support only celery 3.x series. pr welcome
