### ISSUE TITLE
In django1.11.2, I get Error fetching command 'celery on': type object 'Command' has no attribute 'option_list' Command 'djcelerymon' skipped

### ISSUE THREAD

**Issue by pagezhou** [celery/django-celery#537]
I think problem is same as flows:
https://github.com/celery/django-celery/blob/72e6737208705f661198f6b44c279a54c1d1fc55/djcelery/management/commands/djcelerymon.py#L35
but the bug is still exists in djcelery/management/commands/djcelerymon.py

**Comment by auvipy** [comment]
may be it's optparse/argparse issue.
