### ISSUE TITLE
The tasks in the Django 2 admin panel are not correctly displayed

### ISSUE THREAD

**Issue by naprsa** [celery/django-celery#544]
Hello. In the django2 admin panel, the tasks are not correctly displayed, tell me please how can I fix this?

![2018-02-20 0 44 55](https://user-images.githubusercontent.com/24567354/36398274-510d9170-15d7-11e8-8b51-db125e44e22b.png)

**Comment by jxltom** [comment]
I made a PR here https://github.com/celery/django-celery/pull/542
