### ISSUE TITLE
Django 2 incompatible.

### ISSUE THREAD

**Issue by dequn** [celery/django-celery#548]
Since in Django 2 ForeignKey's `on_delete` parameter change to **required**, the dependence *django-kombu* will through  out a runtime error in `/usr/local/lib/python3.6/site-packages/kombu/transport/django/models.py`.

**Comment by zuoakang** [comment]
Can anyone solve this problem?  **waiting**

**Comment by dequn** [comment]
@zuoakang Look at [django2-celery-demo](https://github.com/dequn/django2-celery-demo), it does not must need django-celery.

**Comment by zuoakang** [comment]
@dequn  thanks a lot.

**Comment by stuaxo** [comment]
Hi,
   You can try patching all the `on_delete` calls, the older django default is `on_delete=CASCADE` which may or may not be the right thing.

Best thing is to open a PR with the change and see how review goes.

S

**Comment by maxmalysh** [comment]
To my best knowledge, this was fixed recently. 

I've tried:
- Django 2.1.10
- Celery 3.1.26
- Django-Celery 3.2.2
And it works. 

Let's close the issue?

**Comment by liquidpele** [comment]
Sounds good!
