### ISSUE TITLE
./manage.py djcelerymon fails in Django 1.11

### ISSUE THREAD

**Issue by jwhitlock** [celery/django-celery#549]
``./manage.py djcelerymon --help`` raises an error ``AttributeError: type object 'Command' has no attribute 'option_list'``. This was [deprecated in Django 1.8](https://docs.djangoproject.com/en/2.0/releases/1.8/#extending-management-command-arguments-through-command-option-list), with the switch from argparse to optparse, and [dropped in 1.10](https://docs.djangoproject.com/en/1.11/internals/deprecation/#deprecation-removed-in-1-10).

**Comment by barseghyanartur** [comment]
Any progress on Django 1.11 compatiblity?
