### ISSUE TITLE
Incompatibility with celery 4+

### ISSUE THREAD

**Issue by shirishc** [celery/django-celery#556]
Hi,

Is there any plan to upgrade this to use the latest Celery stable release ? A lot of other packages that I used require Celery 4.0+ ? Or is there any other better way to use Tasks etc rather than using django-celery ?

Any workaround ?

Regards,
Shirish.

**Comment by thedrow** [comment]
This repository is for Celery 3.x. See https://github.com/celery/django-celery-results and https://github.com/celery/django-celery-beat for relevant Django integrations.
