### ISSUE TITLE
Version on pypi looks weird

### ISSUE THREAD

**Issue by stuaxo** [celery/django-celery#572]
Probably not super important, but there are two versions showing on the pypi download page, so I'm not sure which is correct (I think it's 3.2.2)

![image](https://user-images.githubusercontent.com/179677/59502995-314f5780-8e97-11e9-93fa-88a8ec377353.png)

**Comment by liquidpele** [comment]
Looks like someone updated the readme but didn't create the git tag...  @auvipy was 3.3.0 an intended new release?

**Comment by auvipy** [comment]
3.3.0 is the latest version, but on that time readme was forgotten not updated

**Comment by stuaxo** [comment]
Thanks for clarifying.
