### ISSUE TITLE
Please upload v3.3.1 to PyPi

### ISSUE THREAD

**Issue by maxmalysh** [celery/django-celery#578]
Please upload 3.3.1 to PyPi! 

The latest version in PyPi is 3.3.0 and it is completely broken. It won't event start.

**Comment by auvipy** [comment]
ASAP

**Comment by Endzel** [comment]
What is the state on this? I would really really love to have it 😄

**Comment by auvipy** [comment]
allow me to push this today :D

**Comment by Endzel** [comment]
Thank you so much, would definitely consider!

**Comment by auvipy** [comment]
also please try celery 4.4.0rc3

**Comment by Endzel** [comment]
It is not possible to try that celery version alongside this library because of the required dependencies here (celery>=3.1.15,<4.0)

**Comment by auvipy** [comment]
this is celery 3.x only

**Comment by Endzel** [comment]
Understood, thanks again for your quick help 👍
