### ISSUE TITLE
incompatibility with celery

### ISSUE THREAD

**Issue by qkral** [celery/django-celery#608]
I had django-celery v3.3.1 together with celery v4.4.2 for the past few months and everything was OK. Now I cannot add a celery version >4.0 because it says it is incompatible but the problem is that django-celery-results v1.2.1 wants celery>4.0 so I'm stuck there... Please allow django-celery to work with celery 4.4.2 (I see it's a pull request that is already there)

**Comment by auvipy** [comment]
it was always incompatible with celery 4
